### ISSUE TITLE
Mitmekeelne kasutajaliides

### ISSUE THREAD

**Issue by edgarp95** [Volcania/LAFF#1]
Vaja realiseerida 2-3 keelt: eesti keel ja inglise keel kindlasti. Lisaks võib vene keel olla
Käsitsi tõlgitavad asjad inglise keelest - Edgar
Muu funktsionaalsus - Stanislav

**Comment by Zukkari** [comment]
Sain selle probleemi lahendatud ja mitmekeelsus nüüd töötab.
