### ISSUE TITLE
Autentimine

### ISSUE THREAD

**Issue by edgarp95** [Volcania/LAFF#10]
ID kaart - liiga raske
Facebook 
Google
https://courses.cs.ut.ee/2017/vl/spring/Main/Autentimine

**Comment by Zukkari** [comment]
Toimib autentimine, nii parooliga, kui ka facebookiga.

Kõik toimub SocialAuthController klassis. Lisasin mõned kommentaarid ka juurde, kuidas see asi toimib.

Kunagi hiljem tuleks see õige facebooki nupp ka lisada, aga praegu huvitab meid see, et funktsionaalsus on tehtud.
