### ISSUE TITLE
Otsing

### ISSUE THREAD

**Issue by edgarp95** [Volcania/LAFF#27]
Otsingu süsteem võiks baseeruda tagidel

**Comment by languidpie** [comment]
Kas otsing vaatab ainult tage või ka postituse sisu/tiitlit?

**Comment by Zukkari** [comment]
Alguses oli mõte, et ainult tagide põhjal. See oleks minu arust juba piisavalt keeruline.

**Comment by edgarp95** [comment]
Tagid ainuüksi juba piisavalt keeruline. 
Aga kui arendamise käigus tuleb välja, et mingi süsteem oskab paremini, siis võib enda lahendusi ka pakkuda

**Comment by edgarp95** [comment]
Tehtud
