### ISSUE TITLE
Leitud nupp

### ISSUE THREAD

**Issue by edgarp95** [Volcania/LAFF#30]
Kes seal tahtis seda sitta teha, realiseerigu nüüd

**Comment by languidpie** [comment]
Kas saaks andmebaasi lisada lahtri, et kas ta on leitud või mitte?

**Comment by Zukkari** [comment]
Kindlasti. See olekski lahendus. Tabelis oleks veerg leitud väärtustega 0 ja 1. Ning oleks nupp, mis seda väärtust admebaasis vahetab.

**Comment by edgarp95** [comment]
Aga mida antud asi üldse teeb? Nii 1 ja 0 , aga mis sellest muutub? kas nupp kaob? Või mis juhtub, kui nuppu vajutada? Ma ei saa hetkel eriti aru, mida see tegema peaks? Mailto kasutaja email??

**Comment by Zukkari** [comment]
Sul ju seal see kaotatud silt olemas. See nupp muudaks seda siis roheliseks ja tekst oleks leitud ja ongi korras :dancing_men:

**Comment by marcus17777** [comment]
https://www.youtube.com/watch?v=QStEBqy2GI4

**Comment by edgarp95** [comment]
But it's fucking pointless?!? Mailto on ka parem, inimesel kaotatud, siis keegi vajutab, et leidis , siis saaks kontakti inimesega, kes kaotas. Muidu ükskõik mis jorss vajutab ja kohe leidub

**Comment by marcus17777** [comment]
3

**Comment by marcus17777** [comment]
YOU CANT STOP ME

**Comment by languidpie** [comment]
Kui kõrvaline isik vajutab, siis võiks jah mailto olla. Aga kui lisaja ise vajutab, siis võiks panna andmebaasi, et see leitud.

**Comment by edgarp95** [comment]
Okei, see juba parem ja pole raske 
if (auth()-> check()) 
if (auth()->user()->kasutajanimi=postitus.kasutaja) 
funktsioon, mis muudab andmebaasis 
else 
mailto kasutaja
endif
endif

**Comment by edgarp95** [comment]
Ja kui kaotatud pole, siis seda nuppu pole või?

**Comment by languidpie** [comment]
Jah :)

**Comment by edgarp95** [comment]
Realiseeritud triviaalne alternatiiv, kuna nupu ainukeseks tõeliseks ülesandeks oli anda postituse autorile mingit infot, postituse autor saab nvn kustutada enda postitusi ise!
