### ISSUE TITLE
Edit postitustel ja kommentaaridel

### ISSUE THREAD

**Issue by edgarp95** [Volcania/LAFF#33]
See võib aidata https://github.com/mschwarzmueller/laravel-basics-youtube/tree/master/resources/views

**Comment by Zukkari** [comment]
Kommentaaride osa tehtud. On vaja siis teha postitused?

**Comment by languidpie** [comment]
Postitused?

**Comment by Zukkari** [comment]
Postitustel peaks ka edit arvatavasti, kuna äkki kasutaja tahab mingi näpuka parandada. Seda saab teha nago kommentaaride muutmist.
