### ISSUE TITLE
Autoriseerimine

### ISSUE THREAD

**Issue by edgarp95** [Volcania/LAFF#8]
Siin mõeldakse tavalist sisse logimist kasutades selleks parooli ja salasõna, seega eeldab mingite parooliandmete säilitamist andmebaasis - küsida Laurilt, kuidas on mõttekas teha!

**Comment by Zukkari** [comment]
Toimib. Kui kasutaja pole sisse logitud üritab minna '/lisa' lehele, siis suunatakse teda sisselogimis lehele.
